matrix:
  include:
  
    # Flutter Tests
    - os: linux
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        # install Fltuter
        - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
        - ./flutter/bin/flutter doctor
      
      # Run script!
      script:
        - ./flutter/bin/flutter test

    # Android build configuration
    - os: linux
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        # install Fltuter
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - ./flutter/bin/flutter doctor

      # Env. config.
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26

          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra

      jdk: oraclejdk10

      # Run script!c
      script:
        # Gradle requires a build name
        - ./flutter/bin/flutter -v build apk --build-name=ci

    # iOS build configuration
    - os: osx
      before_script:
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller ios-deploy
        - pod setup
        - pip install six
        # install Fltuter
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - ./flutter/bin/flutter doctor

      # Env. config.
      language: generic
      osx_image: xcode9.4

      # Run script!
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache
